

title: Typography
email: des@example.com
description: Hi
baseurl: "/typography/"
url: "" 
twitter_username: d
github_username:  d
destination: docs

# Build settings
plugins:
  - jekyll-feed


exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
